### PR TITLE
Windows fix

### PR DESCRIPTION
**Pull request by lwxbr**
Some modifications to run the plugin in XAMPP 7.3.1 in Windows 10.

### CODE REVIEW

**Comment by lwxbr** [comment]
Note: to work perfectly, the fix of GD Converter must be considered:
https://github.com/rosell-dk/webp-convert/pull/113

**Comment by rosell-dk** [comment]
Thanks a lot!

**Comment by rosell-dk** [comment]
I predict that webp-realizer.php isn't working on Windows? - It is the ability to generate a webp when the *webp* is visited. It now calls `ConvertHelperIndependent::findSourceSeparate` to find source. And that currently uses the following code to decide if $destination is inside the "doc-root" folder of the cache dir:

```php
if (strpos($destination, $imageRoot . '/doc-root/') === 0) {
   ...
}
```

We cannot use realpath in this case, because $destination does not exist yet.

**Comment by lwxbr** [comment]
Yes, you are right, you can't use realpath to normalize directory paths because it only works with real paths are the name of function says, but you can create a function that does that or get a function from a composer module that handle this, it would be interesting look for some module that works both for Linux, Windows and related systems.

**Pull request merged**
